---
- hosts: docker
  become: yes
  remote_user:  centos
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
  - name: Install environment
    raw: ( echo 'https_proxy={{https_proxy}}' >>/etc/environment; echo 'http_proxy={{http_proxy}}' >>/etc/environment )
    #changed_when: False

  - name: Install docker
    raw: ( curl https://releases.rancher.com/install-docker/1.12.sh | sh )
    #changed_when: False

  - pause: seconds=1
      
  - name: reload sytemd
    command: /usr/bin/systemctl daemon-reload

  - name: start docker
    service: name=docker state=started      
         
  - name: enable service docker and ensure it is not masked
    systemd:
      name: docker
      enabled: yes
      masked: no
           
  - name: Check if Service Exists
    stat: path=/etc/init.d/firewalld
    register: service_status
 
  - name: Stop Service
    service: name=firewalld state=stopped
    when: service_status.stat.exists
    register: service_stopped          
 
  - name: Install chrony
    yum: name=chrony
      
  - copy: src=./chrony.conf
       dest=/etc/chrony.conf
     
  - name: Install docker con proxy
       copy: src=./docker.service
       dest=/usr/lib/systemd/system/docker.service
     
 
  - name: install dependencies
    yum: name={{ item  }} state=present
    with_items:
      - tar
      - xz
      - unzip
      - ipset
      - curl
 
  - name: add group nogroup
    group: name=nogroup state=present
 
  - name: disable selinux
    selinux: state=disabled
 
  - copy: src=install_docker/environment
      dest=/etc/environment
 
       
  - name: restart host
    shell: sleep 1;/usr/sbin/reboot
    async: 1
    poll: 0
    ignore_errors: true
 
  - name: waiting for host to come back online
    local_action: wait_for host={{ inventory_hostname }} search_regex=OpenSSH port=22 timeout=300 state=started
